# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.systems_api import SystemsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestSystemsApi(unittest.TestCase):
    """SystemsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.systems_api.SystemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clone_system(self):
        """Test case for clone_system

        Clone system  # noqa: E501
        """
        pass

    def test_create_scenario1(self):
        """Test case for create_scenario1

        Create scenario from system  # noqa: E501
        """
        pass

    def test_create_software_bundle_from_system_module(self):
        """Test case for create_software_bundle_from_system_module

        Create software bundle  # noqa: E501
        """
        pass

    def test_create_system_entire(self):
        """Test case for create_system_entire

        Create system  # noqa: E501
        """
        pass

    def test_get_system(self):
        """Test case for get_system

        Retrieve system  # noqa: E501
        """
        pass

    def test_get_systems(self):
        """Test case for get_systems

        List systems  # noqa: E501
        """
        pass

    def test_get_systems_expanded(self):
        """Test case for get_systems_expanded

        List all systems, including project assets  # noqa: E501
        """
        pass

    def test_quick_build1(self):
        """Test case for quick_build1

        Launch system  # noqa: E501
        """
        pass

    def test_replace_software_asset_for_software_component(self):
        """Test case for replace_software_asset_for_software_component

        Replace software asset  # noqa: E501
        """
        pass

    def test_update_software_component_for_system_module(self):
        """Test case for update_software_component_for_system_module

        Update software component  # noqa: E501
        """
        pass

    def test_update_software_components_for_system_module(self):
        """Test case for update_software_components_for_system_module

        Update software components  # noqa: E501
        """
        pass

    def test_update_software_configuration_for_system_module(self):
        """Test case for update_software_configuration_for_system_module

        Update software configuration  # noqa: E501
        """
        pass

    def test_update_template_profile_for_system_module(self):
        """Test case for update_template_profile_for_system_module

        Update template profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
