# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.models.input_physical_host_all_of import InputPhysicalHostAllOf  # noqa: E501
from cons3rt.rest import ApiException


class TestInputPhysicalHostAllOf(unittest.TestCase):
    """InputPhysicalHostAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputPhysicalHostAllOf(self):
        """Test InputPhysicalHostAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cons3rt.models.input_physical_host_all_of.InputPhysicalHostAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
