# coding: utf-8

"""
    CONS3RT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@cons3rt.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.models.software_component_all_of import SoftwareComponentAllOf  # noqa: E501
from cons3rt.rest import ApiException


class TestSoftwareComponentAllOf(unittest.TestCase):
    """SoftwareComponentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoftwareComponentAllOf(self):
        """Test SoftwareComponentAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cons3rt.models.software_component_all_of.SoftwareComponentAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
