# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_category_to_asset(self):
        """Test case for add_category_to_asset

        """
        pass

    def test_add_network(self):
        """Test case for add_network

        """
        pass

    def test_add_project(self):
        """Test case for add_project

        """
        pass

    def test_add_project_member(self):
        """Test case for add_project_member

        """
        pass

    def test_add_recurring_schedule(self):
        """Test case for add_recurring_schedule

        """
        pass

    def test_add_role_to_project_member(self):
        """Test case for add_role_to_project_member

        """
        pass

    def test_add_submission_service_to_project(self):
        """Test case for add_submission_service_to_project

        """
        pass

    def test_add_team_manager_to_team(self):
        """Test case for add_team_manager_to_team

        """
        pass

    def test_add_trusted_project(self):
        """Test case for add_trusted_project

        """
        pass

    def test_add_trusted_project1(self):
        """Test case for add_trusted_project1

        """
        pass

    def test_add_trusted_project2(self):
        """Test case for add_trusted_project2

        """
        pass

    def test_add_trusted_project3(self):
        """Test case for add_trusted_project3

        """
        pass

    def test_add_trusted_project4(self):
        """Test case for add_trusted_project4

        """
        pass

    def test_add_trusted_project5(self):
        """Test case for add_trusted_project5

        """
        pass

    def test_add_trusted_project6(self):
        """Test case for add_trusted_project6

        """
        pass

    def test_add_trusted_project7(self):
        """Test case for add_trusted_project7

        """
        pass

    def test_allocate_virtualization_realm(self):
        """Test case for allocate_virtualization_realm

        """
        pass

    def test_assign_managing_team(self):
        """Test case for assign_managing_team

        """
        pass

    def test_clone_deployment(self):
        """Test case for clone_deployment

        """
        pass

    def test_clone_scenario(self):
        """Test case for clone_scenario

        """
        pass

    def test_clone_system(self):
        """Test case for clone_system

        """
        pass

    def test_create_category(self):
        """Test case for create_category

        """
        pass

    def test_create_deployment_entire(self):
        """Test case for create_deployment_entire

        """
        pass

    def test_create_project(self):
        """Test case for create_project

        """
        pass

    def test_create_scenario(self):
        """Test case for create_scenario

        """
        pass

    def test_create_scenario1(self):
        """Test case for create_scenario1

        """
        pass

    def test_create_software_asset_bundle_from_system_module(self):
        """Test case for create_software_asset_bundle_from_system_module

        """
        pass

    def test_create_software_bundle_from_system_module(self):
        """Test case for create_software_bundle_from_system_module

        """
        pass

    def test_create_system_asset(self):
        """Test case for create_system_asset

        """
        pass

    def test_create_system_entire(self):
        """Test case for create_system_entire

        """
        pass

    def test_create_team(self):
        """Test case for create_team

        """
        pass

    def test_create_template_subsciption(self):
        """Test case for create_template_subsciption

        """
        pass

    def test_create_user(self):
        """Test case for create_user

        """
        pass

    def test_deallocate_virt_realm(self):
        """Test case for deallocate_virt_realm

        """
        pass

    def test_delete_asset(self):
        """Test case for delete_asset

        """
        pass

    def test_delete_category(self):
        """Test case for delete_category

        """
        pass

    def test_delete_cloud(self):
        """Test case for delete_cloud

        """
        pass

    def test_delete_composition(self):
        """Test case for delete_composition

        """
        pass

    def test_delete_deployment_run(self):
        """Test case for delete_deployment_run

        """
        pass

    def test_delete_network(self):
        """Test case for delete_network

        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        """
        pass

    def test_delete_software_asset_bundle(self):
        """Test case for delete_software_asset_bundle

        """
        pass

    def test_delete_system_asset(self):
        """Test case for delete_system_asset

        """
        pass

    def test_delete_team(self):
        """Test case for delete_team

        """
        pass

    def test_delete_template_subscription(self):
        """Test case for delete_template_subscription

        """
        pass

    def test_determine_valid_virtualization_realms(self):
        """Test case for determine_valid_virtualization_realms

        """
        pass

    def test_disable_virt_realm_remote_access(self):
        """Test case for disable_virt_realm_remote_access

        """
        pass

    def test_download(self):
        """Test case for download

        """
        pass

    def test_download1(self):
        """Test case for download1

        """
        pass

    def test_download2(self):
        """Test case for download2

        """
        pass

    def test_download_deployment_run_test_report(self):
        """Test case for download_deployment_run_test_report

        """
        pass

    def test_download_host(self):
        """Test case for download_host

        """
        pass

    def test_enable_maintence_mode(self):
        """Test case for enable_maintence_mode

        """
        pass

    def test_enable_maintence_mode1(self):
        """Test case for enable_maintence_mode1

        """
        pass

    def test_enable_virt_realm_remote_access(self):
        """Test case for enable_virt_realm_remote_access

        """
        pass

    def test_execute_deployment(self):
        """Test case for execute_deployment

        """
        pass

    def test_get_activity(self):
        """Test case for get_activity

        """
        pass

    def test_get_bindings_for_deployment(self):
        """Test case for get_bindings_for_deployment

        """
        pass

    def test_get_build_number(self):
        """Test case for get_build_number

        """
        pass

    def test_get_build_timestamp(self):
        """Test case for get_build_timestamp

        """
        pass

    def test_get_categories(self):
        """Test case for get_categories

        """
        pass

    def test_get_cloud(self):
        """Test case for get_cloud

        """
        pass

    def test_get_cloud_resources(self):
        """Test case for get_cloud_resources

        """
        pass

    def test_get_clouds(self):
        """Test case for get_clouds

        """
        pass

    def test_get_composition(self):
        """Test case for get_composition

        """
        pass

    def test_get_cons3rt_version(self):
        """Test case for get_cons3rt_version

        """
        pass

    def test_get_container(self):
        """Test case for get_container

        """
        pass

    def test_get_container_assets(self):
        """Test case for get_container_assets

        """
        pass

    def test_get_container_assets_expanded(self):
        """Test case for get_container_assets_expanded

        """
        pass

    def test_get_default_network(self):
        """Test case for get_default_network

        """
        pass

    def test_get_deployment(self):
        """Test case for get_deployment

        """
        pass

    def test_get_deployment_metric(self):
        """Test case for get_deployment_metric

        """
        pass

    def test_get_deployment_run(self):
        """Test case for get_deployment_run

        """
        pass

    def test_get_deployment_run_reports(self):
        """Test case for get_deployment_run_reports

        """
        pass

    def test_get_deployment_runs(self):
        """Test case for get_deployment_runs

        """
        pass

    def test_get_deployment_runs1(self):
        """Test case for get_deployment_runs1

        """
        pass

    def test_get_deployment_runs_in_virtualization_realm(self):
        """Test case for get_deployment_runs_in_virtualization_realm

        """
        pass

    def test_get_deployments(self):
        """Test case for get_deployments

        """
        pass

    def test_get_deployments_expanded(self):
        """Test case for get_deployments_expanded

        """
        pass

    def test_get_edge_gateway_i_ps(self):
        """Test case for get_edge_gateway_i_ps

        """
        pass

    def test_get_environment_string(self):
        """Test case for get_environment_string

        """
        pass

    def test_get_file_content(self):
        """Test case for get_file_content

        """
        pass

    def test_get_file_object(self):
        """Test case for get_file_object

        """
        pass

    def test_get_host(self):
        """Test case for get_host

        """
        pass

    def test_get_host_access(self):
        """Test case for get_host_access

        """
        pass

    def test_get_host_configuration_metrics(self):
        """Test case for get_host_configuration_metrics

        """
        pass

    def test_get_host_configuration_metrics1(self):
        """Test case for get_host_configuration_metrics1

        """
        pass

    def test_get_network(self):
        """Test case for get_network

        """
        pass

    def test_get_networks(self):
        """Test case for get_networks

        """
        pass

    def test_get_pending_users(self):
        """Test case for get_pending_users

        """
        pass

    def test_get_project(self):
        """Test case for get_project

        """
        pass

    def test_get_project_virt_realms(self):
        """Test case for get_project_virt_realms

        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        """
        pass

    def test_get_projects_expanded(self):
        """Test case for get_projects_expanded

        """
        pass

    def test_get_revision(self):
        """Test case for get_revision

        """
        pass

    def test_get_root_html(self):
        """Test case for get_root_html

        """
        pass

    def test_get_root_html1(self):
        """Test case for get_root_html1

        """
        pass

    def test_get_root_html2(self):
        """Test case for get_root_html2

        """
        pass

    def test_get_root_html3(self):
        """Test case for get_root_html3

        """
        pass

    def test_get_scenario(self):
        """Test case for get_scenario

        """
        pass

    def test_get_scenarios(self):
        """Test case for get_scenarios

        """
        pass

    def test_get_scenarios_expanded(self):
        """Test case for get_scenarios_expanded

        """
        pass

    def test_get_service_string(self):
        """Test case for get_service_string

        """
        pass

    def test_get_services_html(self):
        """Test case for get_services_html

        """
        pass

    def test_get_short_version(self):
        """Test case for get_short_version

        """
        pass

    def test_get_software(self):
        """Test case for get_software

        """
        pass

    def test_get_software_asset_bundle_expanded(self):
        """Test case for get_software_asset_bundle_expanded

        """
        pass

    def test_get_software_bundle(self):
        """Test case for get_software_bundle

        """
        pass

    def test_get_software_bundles(self):
        """Test case for get_software_bundles

        """
        pass

    def test_get_software_set(self):
        """Test case for get_software_set

        """
        pass

    def test_get_software_set_expanded(self):
        """Test case for get_software_set_expanded

        """
        pass

    def test_get_system(self):
        """Test case for get_system

        """
        pass

    def test_get_systems(self):
        """Test case for get_systems

        """
        pass

    def test_get_systems_expanded(self):
        """Test case for get_systems_expanded

        """
        pass

    def test_get_team_owned_clouds(self):
        """Test case for get_team_owned_clouds

        """
        pass

    def test_get_team_owned_or_managed_virtualization_realms(self):
        """Test case for get_team_owned_or_managed_virtualization_realms

        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        """
        pass

    def test_get_template_subscription(self):
        """Test case for get_template_subscription

        """
        pass

    def test_get_templates_in_virtualization_realm(self):
        """Test case for get_templates_in_virtualization_realm

        """
        pass

    def test_get_test_asset(self):
        """Test case for get_test_asset

        """
        pass

    def test_get_test_assets(self):
        """Test case for get_test_assets

        """
        pass

    def test_get_test_assets_expanded(self):
        """Test case for get_test_assets_expanded

        """
        pass

    def test_get_unregistered_networks(self):
        """Test case for get_unregistered_networks

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_get_valid_networks_for_virtualization_realm(self):
        """Test case for get_valid_networks_for_virtualization_realm

        """
        pass

    def test_get_version(self):
        """Test case for get_version

        """
        pass

    def test_get_virtual_machine_count_metrics(self):
        """Test case for get_virtual_machine_count_metrics

        """
        pass

    def test_get_virtual_machine_count_metrics1(self):
        """Test case for get_virtual_machine_count_metrics1

        """
        pass

    def test_get_virtualization_realm(self):
        """Test case for get_virtualization_realm

        """
        pass

    def test_get_virtualization_realm_resources(self):
        """Test case for get_virtualization_realm_resources

        """
        pass

    def test_get_virtualization_realms(self):
        """Test case for get_virtualization_realms

        """
        pass

    def test_gettesttools_html(self):
        """Test case for gettesttools_html

        """
        pass

    def test_import_software_asset(self):
        """Test case for import_software_asset

        """
        pass

    def test_import_system_asset(self):
        """Test case for import_system_asset

        """
        pass

    def test_import_test_asset(self):
        """Test case for import_test_asset

        """
        pass

    def test_invalidate_template_cache_in_virtualization_realm(self):
        """Test case for invalidate_template_cache_in_virtualization_realm

        """
        pass

    def test_itar_restrict_asset(self):
        """Test case for itar_restrict_asset

        """
        pass

    def test_itar_restrict_software_asset(self):
        """Test case for itar_restrict_software_asset

        """
        pass

    def test_itar_restrict_test_asset(self):
        """Test case for itar_restrict_test_asset

        """
        pass

    def test_launch_composition(self):
        """Test case for launch_composition

        """
        pass

    def test_launch_deployment(self):
        """Test case for launch_deployment

        """
        pass

    def test_list_composition_status(self):
        """Test case for list_composition_status

        """
        pass

    def test_list_compositions(self):
        """Test case for list_compositions

        """
        pass

    def test_list_dependent_assets(self):
        """Test case for list_dependent_assets

        """
        pass

    def test_list_dependent_assets1(self):
        """Test case for list_dependent_assets1

        """
        pass

    def test_list_dependent_assets2(self):
        """Test case for list_dependent_assets2

        """
        pass

    def test_list_dependent_assets3(self):
        """Test case for list_dependent_assets3

        """
        pass

    def test_list_members(self):
        """Test case for list_members

        """
        pass

    def test_list_options(self):
        """Test case for list_options

        """
        pass

    def test_list_pending_template_subscriptions(self):
        """Test case for list_pending_template_subscriptions

        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        """
        pass

    def test_list_properties(self):
        """Test case for list_properties

        """
        pass

    def test_list_schedules(self):
        """Test case for list_schedules

        """
        pass

    def test_list_submission_serivces_for_project(self):
        """Test case for list_submission_serivces_for_project

        """
        pass

    def test_list_system_assets(self):
        """Test case for list_system_assets

        """
        pass

    def test_list_template_registrations(self):
        """Test case for list_template_registrations

        """
        pass

    def test_list_template_subscriptions(self):
        """Test case for list_template_subscriptions

        """
        pass

    def test_list_unregistered_templates(self):
        """Test case for list_unregistered_templates

        """
        pass

    def test_list_virt_realms_in_cloud(self):
        """Test case for list_virt_realms_in_cloud

        """
        pass

    def test_list_virtualization_realm_templates(self):
        """Test case for list_virtualization_realm_templates

        """
        pass

    def test_perform_host_action(self):
        """Test case for perform_host_action

        """
        pass

    def test_publish_deployment_run(self):
        """Test case for publish_deployment_run

        """
        pass

    def test_publish_scenario_to_composition(self):
        """Test case for publish_scenario_to_composition

        """
        pass

    def test_quick_build(self):
        """Test case for quick_build

        """
        pass

    def test_quick_build1(self):
        """Test case for quick_build1

        """
        pass

    def test_redeploy_container_asset(self):
        """Test case for redeploy_container_asset

        """
        pass

    def test_redeploy_edges(self):
        """Test case for redeploy_edges

        """
        pass

    def test_register_cloud(self):
        """Test case for register_cloud

        """
        pass

    def test_register_network(self):
        """Test case for register_network

        """
        pass

    def test_register_template(self):
        """Test case for register_template

        """
        pass

    def test_register_virtualization_realm(self):
        """Test case for register_virtualization_realm

        """
        pass

    def test_relaunch_deployment_run(self):
        """Test case for relaunch_deployment_run

        """
        pass

    def test_release_deployment_run(self):
        """Test case for release_deployment_run

        """
        pass

    def test_remove_category_from_asset(self):
        """Test case for remove_category_from_asset

        """
        pass

    def test_remove_project(self):
        """Test case for remove_project

        """
        pass

    def test_remove_project_member(self):
        """Test case for remove_project_member

        """
        pass

    def test_remove_recurring_schedule(self):
        """Test case for remove_recurring_schedule

        """
        pass

    def test_remove_role_from_project_member(self):
        """Test case for remove_role_from_project_member

        """
        pass

    def test_remove_submission_service_from_project(self):
        """Test case for remove_submission_service_from_project

        """
        pass

    def test_remove_team_manager_from_team(self):
        """Test case for remove_team_manager_from_team

        """
        pass

    def test_remove_trusted_project(self):
        """Test case for remove_trusted_project

        """
        pass

    def test_remove_trusted_project1(self):
        """Test case for remove_trusted_project1

        """
        pass

    def test_remove_trusted_project2(self):
        """Test case for remove_trusted_project2

        """
        pass

    def test_remove_trusted_project3(self):
        """Test case for remove_trusted_project3

        """
        pass

    def test_remove_trusted_project4(self):
        """Test case for remove_trusted_project4

        """
        pass

    def test_remove_trusted_project5(self):
        """Test case for remove_trusted_project5

        """
        pass

    def test_remove_trusted_project6(self):
        """Test case for remove_trusted_project6

        """
        pass

    def test_remove_trusted_project7(self):
        """Test case for remove_trusted_project7

        """
        pass

    def test_remove_virt_realm(self):
        """Test case for remove_virt_realm

        """
        pass

    def test_replace_software_asset_for_software_component(self):
        """Test case for replace_software_asset_for_software_component

        """
        pass

    def test_request_project_invitation(self):
        """Test case for request_project_invitation

        """
        pass

    def test_retest_deployment_run(self):
        """Test case for retest_deployment_run

        """
        pass

    def test_retrieve_system_asset(self):
        """Test case for retrieve_system_asset

        """
        pass

    def test_retrieve_team(self):
        """Test case for retrieve_team

        """
        pass

    def test_retrieve_template_registration(self):
        """Test case for retrieve_template_registration

        """
        pass

    def test_search(self):
        """Test case for search

        """
        pass

    def test_set_category_parent(self):
        """Test case for set_category_parent

        """
        pass

    def test_set_deployment_run_lock(self):
        """Test case for set_deployment_run_lock

        """
        pass

    def test_set_power_schedule_for_deployment_run(self):
        """Test case for set_power_schedule_for_deployment_run

        """
        pass

    def test_set_project_default_power_schedule(self):
        """Test case for set_project_default_power_schedule

        """
        pass

    def test_set_project_default_virtualization_realm(self):
        """Test case for set_project_default_virtualization_realm

        """
        pass

    def test_set_project_itar_information(self):
        """Test case for set_project_itar_information

        """
        pass

    def test_set_project_limits(self):
        """Test case for set_project_limits

        """
        pass

    def test_set_virtualization_realm_active(self):
        """Test case for set_virtualization_realm_active

        """
        pass

    def test_share_template_registration(self):
        """Test case for share_template_registration

        """
        pass

    def test_submit_asset_to_submission_service(self):
        """Test case for submit_asset_to_submission_service

        """
        pass

    def test_unassign_managing_team(self):
        """Test case for unassign_managing_team

        """
        pass

    def test_unregister_template(self):
        """Test case for unregister_template

        """
        pass

    def test_unshare_template_registration(self):
        """Test case for unshare_template_registration

        """
        pass

    def test_update_asset(self):
        """Test case for update_asset

        """
        pass

    def test_update_asset_content(self):
        """Test case for update_asset_content

        """
        pass

    def test_update_asset_state(self):
        """Test case for update_asset_state

        """
        pass

    def test_update_asset_visibility_query(self):
        """Test case for update_asset_visibility_query

        """
        pass

    def test_update_category(self):
        """Test case for update_category

        """
        pass

    def test_update_cloud(self):
        """Test case for update_cloud

        """
        pass

    def test_update_composition(self):
        """Test case for update_composition

        """
        pass

    def test_update_deployment(self):
        """Test case for update_deployment

        """
        pass

    def test_update_deployment_state(self):
        """Test case for update_deployment_state

        """
        pass

    def test_update_deployment_visibility_query(self):
        """Test case for update_deployment_visibility_query

        """
        pass

    def test_update_impact_level(self):
        """Test case for update_impact_level

        """
        pass

    def test_update_instance_limit(self):
        """Test case for update_instance_limit

        """
        pass

    def test_update_instance_limit1(self):
        """Test case for update_instance_limit1

        """
        pass

    def test_update_offline_status(self):
        """Test case for update_offline_status

        """
        pass

    def test_update_project(self):
        """Test case for update_project

        """
        pass

    def test_update_scenario(self):
        """Test case for update_scenario

        """
        pass

    def test_update_software_asset(self):
        """Test case for update_software_asset

        """
        pass

    def test_update_software_asset_bundle(self):
        """Test case for update_software_asset_bundle

        """
        pass

    def test_update_software_asset_content(self):
        """Test case for update_software_asset_content

        """
        pass

    def test_update_software_asset_impact_level(self):
        """Test case for update_software_asset_impact_level

        """
        pass

    def test_update_software_asset_install_script(self):
        """Test case for update_software_asset_install_script

        """
        pass

    def test_update_software_component_for_system_module(self):
        """Test case for update_software_component_for_system_module

        """
        pass

    def test_update_software_components_for_system_module(self):
        """Test case for update_software_components_for_system_module

        """
        pass

    def test_update_software_configuration_for_system_module(self):
        """Test case for update_software_configuration_for_system_module

        """
        pass

    def test_update_state(self):
        """Test case for update_state

        """
        pass

    def test_update_state1(self):
        """Test case for update_state1

        """
        pass

    def test_update_state2(self):
        """Test case for update_state2

        """
        pass

    def test_update_state3(self):
        """Test case for update_state3

        """
        pass

    def test_update_state4(self):
        """Test case for update_state4

        """
        pass

    def test_update_submission_service(self):
        """Test case for update_submission_service

        """
        pass

    def test_update_system(self):
        """Test case for update_system

        """
        pass

    def test_update_system_asset(self):
        """Test case for update_system_asset

        """
        pass

    def test_update_team(self):
        """Test case for update_team

        """
        pass

    def test_update_team_state(self):
        """Test case for update_team_state

        """
        pass

    def test_update_template_profile_for_system_module(self):
        """Test case for update_template_profile_for_system_module

        """
        pass

    def test_update_template_registration(self):
        """Test case for update_template_registration

        """
        pass

    def test_update_template_subscription(self):
        """Test case for update_template_subscription

        """
        pass

    def test_update_test_asset(self):
        """Test case for update_test_asset

        """
        pass

    def test_update_test_asset_content(self):
        """Test case for update_test_asset_content

        """
        pass

    def test_update_test_asset_impact_level(self):
        """Test case for update_test_asset_impact_level

        """
        pass

    def test_update_virt_realm(self):
        """Test case for update_virt_realm

        """
        pass

    def test_update_virt_realm_remote_access_config(self):
        """Test case for update_virt_realm_remote_access_config

        """
        pass

    def test_update_virtualization_realm(self):
        """Test case for update_virtualization_realm

        """
        pass

    def test_update_virtualization_realm_maximum_impact_level(self):
        """Test case for update_virtualization_realm_maximum_impact_level

        """
        pass

    def test_update_visibility_query(self):
        """Test case for update_visibility_query

        """
        pass

    def test_update_visibility_query1(self):
        """Test case for update_visibility_query1

        """
        pass

    def test_update_visibility_query2(self):
        """Test case for update_visibility_query2

        """
        pass

    def test_update_visibility_query3(self):
        """Test case for update_visibility_query3

        """
        pass

    def test_update_visibility_query4(self):
        """Test case for update_visibility_query4

        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        """
        pass

    def test_upload_file1(self):
        """Test case for upload_file1

        """
        pass

    def test_validate_credentials(self):
        """Test case for validate_credentials

        """
        pass


if __name__ == '__main__':
    unittest.main()
