# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.software_bundles_api import SoftwareBundlesApi  # noqa: E501
from cons3rt.rest import ApiException


class TestSoftwareBundlesApi(unittest.TestCase):
    """SoftwareBundlesApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.software_bundles_api.SoftwareBundlesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_software_asset_bundle_from_system_module(self):
        """Test case for create_software_asset_bundle_from_system_module

        Create software bundle  # noqa: E501
        """
        pass

    def test_delete_software_asset_bundle(self):
        """Test case for delete_software_asset_bundle

        Delete software bundle  # noqa: E501
        """
        pass

    def test_get_software_asset_bundle_expanded(self):
        """Test case for get_software_asset_bundle_expanded

        List all software bundles, including project assets  # noqa: E501
        """
        pass

    def test_get_software_bundle(self):
        """Test case for get_software_bundle

        Retrieve software bundle  # noqa: E501
        """
        pass

    def test_get_software_bundles(self):
        """Test case for get_software_bundles

        List software bundles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
