# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.models.input_open_stack_client import InputOpenStackClient  # noqa: E501
from cons3rt.rest import ApiException


class TestInputOpenStackClient(unittest.TestCase):
    """InputOpenStackClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputOpenStackClient(self):
        """Test InputOpenStackClient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cons3rt.models.input_open_stack_client.InputOpenStackClient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
