# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.client_api import ClientApi  # noqa: E501
from cons3rt.rest import ApiException


class TestClientApi(unittest.TestCase):
    """ClientApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.client_api.ClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_launch_composition(self):
        """Test case for launch_composition

        Launch composition  # noqa: E501
        """
        pass

    def test_list_composition_status(self):
        """Test case for list_composition_status

        List composition statuses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
