# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.projects_api import ProjectsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project_member(self):
        """Test case for add_project_member

        Assign project member  # noqa: E501
        """
        pass

    def test_add_role_to_project_member(self):
        """Test case for add_role_to_project_member

        Assign role to member  # noqa: E501
        """
        pass

    def test_add_submission_service_to_project(self):
        """Test case for add_submission_service_to_project

        Add submission service  # noqa: E501
        """
        pass

    def test_add_trusted_project1(self):
        """Test case for add_trusted_project1

        Assign trusted project to project  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a project  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete project  # noqa: E501
        """
        pass

    def test_get_host_configuration_metrics(self):
        """Test case for get_host_configuration_metrics

        Retrieve metrics  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Retrieve project  # noqa: E501
        """
        pass

    def test_get_project_virt_realms(self):
        """Test case for get_project_virt_realms

        List virtualization realms  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        List joined projects  # noqa: E501
        """
        pass

    def test_get_projects_expanded(self):
        """Test case for get_projects_expanded

        List unjoined projects  # noqa: E501
        """
        pass

    def test_get_virtual_machine_count_metrics(self):
        """Test case for get_virtual_machine_count_metrics

        Retrieve virtual machine metrics  # noqa: E501
        """
        pass

    def test_list_members(self):
        """Test case for list_members

        List members  # noqa: E501
        """
        pass

    def test_list_submission_serivces_for_project(self):
        """Test case for list_submission_serivces_for_project

        List submission services  # noqa: E501
        """
        pass

    def test_remove_project_member(self):
        """Test case for remove_project_member

        Unassign member from project  # noqa: E501
        """
        pass

    def test_remove_role_from_project_member(self):
        """Test case for remove_role_from_project_member

        Unassign role from member  # noqa: E501
        """
        pass

    def test_remove_submission_service_from_project(self):
        """Test case for remove_submission_service_from_project

        Remove submission service  # noqa: E501
        """
        pass

    def test_remove_trusted_project1(self):
        """Test case for remove_trusted_project1

        Unassign trusted project from project  # noqa: E501
        """
        pass

    def test_request_project_invitation(self):
        """Test case for request_project_invitation

        Create invitation code  # noqa: E501
        """
        pass

    def test_set_project_default_power_schedule(self):
        """Test case for set_project_default_power_schedule

        Update default power schedule  # noqa: E501
        """
        pass

    def test_set_project_default_virtualization_realm(self):
        """Test case for set_project_default_virtualization_realm

        Update default virtualization realm  # noqa: E501
        """
        pass

    def test_set_project_itar_information(self):
        """Test case for set_project_itar_information

        Set asset export restriction  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update project  # noqa: E501
        """
        pass

    def test_update_submission_service(self):
        """Test case for update_submission_service

        Update submission service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
