# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.test_tools_api import TestToolsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestTestToolsApi(unittest.TestCase):
    """TestToolsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.test_tools_api.TestToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gettesttools_html(self):
        """Test case for gettesttools_html

        Get Test Tool HTML  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
