# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.compositions_api import CompositionsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestCompositionsApi(unittest.TestCase):
    """CompositionsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.compositions_api.CompositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_composition(self):
        """Test case for delete_composition

        Delete composition  # noqa: E501
        """
        pass

    def test_get_composition(self):
        """Test case for get_composition

        Retrieve composition  # noqa: E501
        """
        pass

    def test_list_compositions(self):
        """Test case for list_compositions

        List all compositions  # noqa: E501
        """
        pass

    def test_update_composition(self):
        """Test case for update_composition

        Update composition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
