# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.models.input_unregister_template_object import InputUnregisterTemplateObject  # noqa: E501
from cons3rt.rest import ApiException


class TestInputUnregisterTemplateObject(unittest.TestCase):
    """InputUnregisterTemplateObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputUnregisterTemplateObject(self):
        """Test InputUnregisterTemplateObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cons3rt.models.input_unregister_template_object.InputUnregisterTemplateObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
