# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.models.input_sftp_submission_endpoint_for_asset_submission import InputSFTPSubmissionEndpointForAssetSubmission  # noqa: E501
from cons3rt.rest import ApiException


class TestInputSFTPSubmissionEndpointForAssetSubmission(unittest.TestCase):
    """InputSFTPSubmissionEndpointForAssetSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputSFTPSubmissionEndpointForAssetSubmission(self):
        """Test InputSFTPSubmissionEndpointForAssetSubmission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cons3rt.models.input_sftp_submission_endpoint_for_asset_submission.InputSFTPSubmissionEndpointForAssetSubmission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
