# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.container_assets_api import ContainerAssetsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestContainerAssetsApi(unittest.TestCase):
    """ContainerAssetsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.container_assets_api.ContainerAssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_container(self):
        """Test case for get_container

        Retrieve container asset  # noqa: E501
        """
        pass

    def test_get_container_assets(self):
        """Test case for get_container_assets

        List all containers  # noqa: E501
        """
        pass

    def test_get_container_assets_expanded(self):
        """Test case for get_container_assets_expanded

        List all containers, including project assets  # noqa: E501
        """
        pass

    def test_submit_asset_to_submission_service(self):
        """Test case for submit_asset_to_submission_service

        Submit container to the project's submission service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
