# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: Fred@gigagantic-server.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cons3rt
from cons3rt.api.clouds_api import CloudsApi  # noqa: E501
from cons3rt.rest import ApiException


class TestCloudsApi(unittest.TestCase):
    """CloudsApi unit test stubs"""

    def setUp(self):
        self.api = cons3rt.api.clouds_api.CloudsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project(self):
        """Test case for add_project

        Assign project  # noqa: E501
        """
        pass

    def test_allocate_virtualization_realm(self):
        """Test case for allocate_virtualization_realm

        Allocate virtualization realm  # noqa: E501
        """
        pass

    def test_assign_managing_team(self):
        """Test case for assign_managing_team

        Assign virtualization realm managing team  # noqa: E501
        """
        pass

    def test_deallocate_virt_realm(self):
        """Test case for deallocate_virt_realm

        De-allocate virtualization realm  # noqa: E501
        """
        pass

    def test_delete_cloud(self):
        """Test case for delete_cloud

        Delete cloud  # noqa: E501
        """
        pass

    def test_enable_maintence_mode(self):
        """Test case for enable_maintence_mode

        Update maintenance mode  # noqa: E501
        """
        pass

    def test_get_cloud(self):
        """Test case for get_cloud

        Retrieve cloud  # noqa: E501
        """
        pass

    def test_get_cloud_resources(self):
        """Test case for get_cloud_resources

        Retrieve cloud resources  # noqa: E501
        """
        pass

    def test_get_clouds(self):
        """Test case for get_clouds

        List clouds  # noqa: E501
        """
        pass

    def test_get_default_network(self):
        """Test case for get_default_network

        Retrieve default network  # noqa: E501
        """
        pass

    def test_get_edge_gateway_i_ps(self):
        """Test case for get_edge_gateway_i_ps

        List edge gateways  # noqa: E501
        """
        pass

    def test_list_virt_realms_in_cloud(self):
        """Test case for list_virt_realms_in_cloud

        List virtualization realms  # noqa: E501
        """
        pass

    def test_register_cloud(self):
        """Test case for register_cloud

        Create cloud  # noqa: E501
        """
        pass

    def test_register_virtualization_realm(self):
        """Test case for register_virtualization_realm

        Register virtualization realm  # noqa: E501
        """
        pass

    def test_remove_virt_realm(self):
        """Test case for remove_virt_realm

        Unregister virtualization realm  # noqa: E501
        """
        pass

    def test_unassign_managing_team(self):
        """Test case for unassign_managing_team

        Unassign manager from team  # noqa: E501
        """
        pass

    def test_update_cloud(self):
        """Test case for update_cloud

        Update cloud  # noqa: E501
        """
        pass

    def test_update_virt_realm(self):
        """Test case for update_virt_realm

        Update virtualization realm  # noqa: E501
        """
        pass

    def test_update_virtualization_realm(self):
        """Test case for update_virtualization_realm

        Update virtualization realm  # noqa: E501
        """
        pass

    def test_update_virtualization_realm_maximum_impact_level(self):
        """Test case for update_virtualization_realm_maximum_impact_level

        Update impact level  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
