# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.v_cloud_cloud_space_request_all_of import VCloudCloudSpaceRequestAllOf  # noqa: E501
from openapi_client.rest import ApiException


class TestVCloudCloudSpaceRequestAllOf(unittest.TestCase):
    """VCloudCloudSpaceRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVCloudCloudSpaceRequestAllOf(self):
        """Test VCloudCloudSpaceRequestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.v_cloud_cloud_space_request_all_of.VCloudCloudSpaceRequestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
