# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class MinimalCategory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'disruptive': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'disruptive': 'disruptive'
    }

    def __init__(self, id=None, name=None, disruptive=None, local_vars_configuration=None):  # noqa: E501
        """MinimalCategory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._disruptive = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if disruptive is not None:
            self.disruptive = disruptive

    @property
    def id(self):
        """Gets the id of this MinimalCategory.  # noqa: E501


        :return: The id of this MinimalCategory.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MinimalCategory.


        :param id: The id of this MinimalCategory.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MinimalCategory.  # noqa: E501


        :return: The name of this MinimalCategory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MinimalCategory.


        :param name: The name of this MinimalCategory.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def disruptive(self):
        """Gets the disruptive of this MinimalCategory.  # noqa: E501


        :return: The disruptive of this MinimalCategory.  # noqa: E501
        :rtype: bool
        """
        return self._disruptive

    @disruptive.setter
    def disruptive(self, disruptive):
        """Sets the disruptive of this MinimalCategory.


        :param disruptive: The disruptive of this MinimalCategory.  # noqa: E501
        :type: bool
        """

        self._disruptive = disruptive

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MinimalCategory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MinimalCategory):
            return True

        return self.to_dict() != other.to_dict()
