# coding: utf-8

"""
    CONS3RT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@cons3rt.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cons3rt.configuration import Configuration


class ContainerConfiguration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'port_mappings': 'list[ContainerPortMapping]',
        'container_name': 'str',
        'run_arguments': 'str',
        'environment_map': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'id',
        'port_mappings': 'portMappings',
        'container_name': 'containerName',
        'run_arguments': 'runArguments',
        'environment_map': 'environmentMap'
    }

    def __init__(self, id=None, port_mappings=None, container_name=None, run_arguments=None, environment_map=None, local_vars_configuration=None):  # noqa: E501
        """ContainerConfiguration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._port_mappings = None
        self._container_name = None
        self._run_arguments = None
        self._environment_map = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if port_mappings is not None:
            self.port_mappings = port_mappings
        self.container_name = container_name
        if run_arguments is not None:
            self.run_arguments = run_arguments
        if environment_map is not None:
            self.environment_map = environment_map

    @property
    def id(self):
        """Gets the id of this ContainerConfiguration.  # noqa: E501


        :return: The id of this ContainerConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ContainerConfiguration.


        :param id: The id of this ContainerConfiguration.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def port_mappings(self):
        """Gets the port_mappings of this ContainerConfiguration.  # noqa: E501


        :return: The port_mappings of this ContainerConfiguration.  # noqa: E501
        :rtype: list[ContainerPortMapping]
        """
        return self._port_mappings

    @port_mappings.setter
    def port_mappings(self, port_mappings):
        """Sets the port_mappings of this ContainerConfiguration.


        :param port_mappings: The port_mappings of this ContainerConfiguration.  # noqa: E501
        :type: list[ContainerPortMapping]
        """

        self._port_mappings = port_mappings

    @property
    def container_name(self):
        """Gets the container_name of this ContainerConfiguration.  # noqa: E501


        :return: The container_name of this ContainerConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._container_name

    @container_name.setter
    def container_name(self, container_name):
        """Sets the container_name of this ContainerConfiguration.


        :param container_name: The container_name of this ContainerConfiguration.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and container_name is None:  # noqa: E501
            raise ValueError("Invalid value for `container_name`, must not be `None`")  # noqa: E501

        self._container_name = container_name

    @property
    def run_arguments(self):
        """Gets the run_arguments of this ContainerConfiguration.  # noqa: E501


        :return: The run_arguments of this ContainerConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._run_arguments

    @run_arguments.setter
    def run_arguments(self, run_arguments):
        """Sets the run_arguments of this ContainerConfiguration.


        :param run_arguments: The run_arguments of this ContainerConfiguration.  # noqa: E501
        :type: str
        """

        self._run_arguments = run_arguments

    @property
    def environment_map(self):
        """Gets the environment_map of this ContainerConfiguration.  # noqa: E501


        :return: The environment_map of this ContainerConfiguration.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._environment_map

    @environment_map.setter
    def environment_map(self, environment_map):
        """Sets the environment_map of this ContainerConfiguration.


        :param environment_map: The environment_map of this ContainerConfiguration.  # noqa: E501
        :type: dict(str, str)
        """

        self._environment_map = environment_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerConfiguration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContainerConfiguration):
            return True

        return self.to_dict() != other.to_dict()
