# coding: utf-8

"""
    CONS3RT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@cons3rt.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cons3rt.configuration import Configuration


class InputPhysicalHost(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'physical_machine': 'InputPhysicalMachine',
        'components': 'list[InputAbstractComponent]'
    }

    attribute_map = {
        'name': 'name',
        'physical_machine': 'physicalMachine',
        'components': 'components'
    }

    def __init__(self, name=None, physical_machine=None, components=None, local_vars_configuration=None):  # noqa: E501
        """InputPhysicalHost - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._physical_machine = None
        self._components = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if physical_machine is not None:
            self.physical_machine = physical_machine
        if components is not None:
            self.components = components

    @property
    def name(self):
        """Gets the name of this InputPhysicalHost.  # noqa: E501


        :return: The name of this InputPhysicalHost.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InputPhysicalHost.


        :param name: The name of this InputPhysicalHost.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def physical_machine(self):
        """Gets the physical_machine of this InputPhysicalHost.  # noqa: E501


        :return: The physical_machine of this InputPhysicalHost.  # noqa: E501
        :rtype: InputPhysicalMachine
        """
        return self._physical_machine

    @physical_machine.setter
    def physical_machine(self, physical_machine):
        """Sets the physical_machine of this InputPhysicalHost.


        :param physical_machine: The physical_machine of this InputPhysicalHost.  # noqa: E501
        :type: InputPhysicalMachine
        """

        self._physical_machine = physical_machine

    @property
    def components(self):
        """Gets the components of this InputPhysicalHost.  # noqa: E501


        :return: The components of this InputPhysicalHost.  # noqa: E501
        :rtype: list[InputAbstractComponent]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this InputPhysicalHost.


        :param components: The components of this InputPhysicalHost.  # noqa: E501
        :type: list[InputAbstractComponent]
        """

        self._components = components

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputPhysicalHost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InputPhysicalHost):
            return True

        return self.to_dict() != other.to_dict()
