# coding: utf-8

"""
    CONS3RT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@cons3rt.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cons3rt.configuration import Configuration


class InputAwsVirtualizationRealmAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'region': 'str',
        'vpc_id': 'str'
    }

    attribute_map = {
        'region': 'region',
        'vpc_id': 'vpcId'
    }

    def __init__(self, region=None, vpc_id=None, local_vars_configuration=None):  # noqa: E501
        """InputAwsVirtualizationRealmAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._region = None
        self._vpc_id = None
        self.discriminator = None

        if region is not None:
            self.region = region
        if vpc_id is not None:
            self.vpc_id = vpc_id

    @property
    def region(self):
        """Gets the region of this InputAwsVirtualizationRealmAllOf.  # noqa: E501


        :return: The region of this InputAwsVirtualizationRealmAllOf.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this InputAwsVirtualizationRealmAllOf.


        :param region: The region of this InputAwsVirtualizationRealmAllOf.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def vpc_id(self):
        """Gets the vpc_id of this InputAwsVirtualizationRealmAllOf.  # noqa: E501


        :return: The vpc_id of this InputAwsVirtualizationRealmAllOf.  # noqa: E501
        :rtype: str
        """
        return self._vpc_id

    @vpc_id.setter
    def vpc_id(self, vpc_id):
        """Sets the vpc_id of this InputAwsVirtualizationRealmAllOf.


        :param vpc_id: The vpc_id of this InputAwsVirtualizationRealmAllOf.  # noqa: E501
        :type: str
        """

        self._vpc_id = vpc_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputAwsVirtualizationRealmAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InputAwsVirtualizationRealmAllOf):
            return True

        return self.to_dict() != other.to_dict()
