# coding: utf-8

"""
    CONS3RT Web API

    A CONS3RT ReSTful API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cons3rt.configuration import Configuration


class UnregisterTemplateObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'client': 'VirtualizationRealmClient',
        'remove_subscriptions': 'bool'
    }

    attribute_map = {
        'client': 'client',
        'remove_subscriptions': 'removeSubscriptions'
    }

    def __init__(self, client=None, remove_subscriptions=None, local_vars_configuration=None):  # noqa: E501
        """UnregisterTemplateObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._client = None
        self._remove_subscriptions = None
        self.discriminator = None

        if client is not None:
            self.client = client
        self.remove_subscriptions = remove_subscriptions

    @property
    def client(self):
        """Gets the client of this UnregisterTemplateObject.  # noqa: E501


        :return: The client of this UnregisterTemplateObject.  # noqa: E501
        :rtype: VirtualizationRealmClient
        """
        return self._client

    @client.setter
    def client(self, client):
        """Sets the client of this UnregisterTemplateObject.


        :param client: The client of this UnregisterTemplateObject.  # noqa: E501
        :type: VirtualizationRealmClient
        """

        self._client = client

    @property
    def remove_subscriptions(self):
        """Gets the remove_subscriptions of this UnregisterTemplateObject.  # noqa: E501


        :return: The remove_subscriptions of this UnregisterTemplateObject.  # noqa: E501
        :rtype: bool
        """
        return self._remove_subscriptions

    @remove_subscriptions.setter
    def remove_subscriptions(self, remove_subscriptions):
        """Sets the remove_subscriptions of this UnregisterTemplateObject.


        :param remove_subscriptions: The remove_subscriptions of this UnregisterTemplateObject.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and remove_subscriptions is None:  # noqa: E501
            raise ValueError("Invalid value for `remove_subscriptions`, must not be `None`")  # noqa: E501

        self._remove_subscriptions = remove_subscriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnregisterTemplateObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UnregisterTemplateObject):
            return True

        return self.to_dict() != other.to_dict()
